# Generated by Django 6.0.6 on 2026-07-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('course', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('address', models.TextField()),
                ('pwd', models.TextField()),
            ],
        ),
    ]
